import { Area } from '@/types';

function uid(): string {
  return Math.random().toString(36).slice(2, 11);
}

const COLORS = ['#C9B99A', '#A8B5A2', '#B0B8C8', '#C4B0C8', '#D4C5A9', '#B5C4B1'];

export const INITIAL_DATA: Area[] = [
  {
    id: uid(),
    name: 'Etapas de Projeto',
    order_index: 0,
    phases: [
      {
        id: uid(),
        name: 'Fase 1 — Briefing',
        order_index: 0,
        color: COLORS[0],
        steps: [
          {
            id: uid(),
            name: 'Entrevista de briefing com o cliente',
            responsible: 'Ana ou Mariana',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 0,
            ai_points: [],
          },
        ],
      },
      {
        id: uid(),
        name: 'Fase 2 — Levantamento',
        order_index: 1,
        color: COLORS[1],
        steps: [
          {
            id: uid(),
            name: 'Recebimento do material de levantamento',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 0,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Modelagem no Revit',
            responsible: '',
            estimated_time: '',
            tools: 'Revit',
            notes: '',
            order_index: 1,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Conferência e correção do levantamento',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 2,
            ai_points: [],
          },
        ],
      },
      {
        id: uid(),
        name: 'Fase 3 — Estudo Preliminar / Criação',
        order_index: 2,
        color: COLORS[2],
        steps: [
          {
            id: uid(),
            name: 'Primeiros estudos e partido do projeto',
            responsible: 'Ana ou Mariana',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 0,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Modelagem 3D',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 1,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Aprovação interna do 3D',
            responsible: 'Ana ou Mariana',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 2,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Finalização da apresentação',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 3,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Apresentação ao cliente e aprovação',
            responsible: 'Ana ou Mariana',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 4,
            ai_points: [],
          },
        ],
      },
      {
        id: uid(),
        name: 'Fase 4 — Detalhamento pós-aprovação',
        order_index: 3,
        color: COLORS[3],
        steps: [
          {
            id: uid(),
            name: 'Maquete executiva',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 0,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Lista de mobiliário',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 1,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Apresentação de armários',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 2,
            ai_points: [],
          },
        ],
      },
      {
        id: uid(),
        name: 'Fase 5 — Executivo',
        order_index: 4,
        color: COLORS[4],
        steps: [
          {
            id: uid(),
            name: 'Definição de execução do executivo',
            responsible: 'Ana ou Mariana',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 0,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Produção do Caderno de Obras',
            responsible: '',
            estimated_time: '',
            tools: 'Revit',
            notes: '',
            order_index: 1,
            ai_points: [],
          },
          {
            id: uid(),
            name: '1ª correção — Caderno de Obras',
            responsible: 'Fernanda',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 2,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Correções pelo executor — Caderno de Obras',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 3,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Leitura final — Caderno de Obras',
            responsible: 'Fernanda',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 4,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Produção do Caderno de Finalização',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 5,
            ai_points: [],
          },
          {
            id: uid(),
            name: '1ª correção — Caderno de Finalização',
            responsible: 'Fernanda ou Thalia',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 6,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Correções pelo executor — Caderno de Finalização',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 7,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Leitura final — Caderno de Finalização',
            responsible: 'Fernanda ou Thalia',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 8,
            ai_points: [],
          },
        ],
      },
    ],
  },
  {
    id: uid(),
    name: 'Administrativo',
    order_index: 1,
    phases: [
      {
        id: uid(),
        name: 'Contratos e Clientes',
        order_index: 0,
        color: COLORS[0],
        steps: [
          {
            id: uid(),
            name: 'Elaboração e envio de proposta',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 0,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Assinatura de contrato',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 1,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Onboarding do cliente',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 2,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Acompanhamento e comunicação durante o projeto',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 3,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Encerramento e entrega ao cliente',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 4,
            ai_points: [],
          },
        ],
      },
      {
        id: uid(),
        name: 'Equipe e Fornecedores',
        order_index: 1,
        color: COLORS[2],
        steps: [
          {
            id: uid(),
            name: 'Contratação e integração de colaboradores',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 0,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Gestão de freelancers',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 1,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Relacionamento com fornecedores',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 2,
            ai_points: [],
          },
        ],
      },
    ],
  },
  {
    id: uid(),
    name: 'Financeiro',
    order_index: 2,
    phases: [
      {
        id: uid(),
        name: 'Faturamento e Recebimento',
        order_index: 0,
        color: COLORS[1],
        steps: [
          {
            id: uid(),
            name: 'Emissão de nota fiscal / cobrança',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 0,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Controle de pagamentos recebidos',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 1,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Cobrança de inadimplentes',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 2,
            ai_points: [],
          },
        ],
      },
      {
        id: uid(),
        name: 'Controle e Planejamento',
        order_index: 1,
        color: COLORS[3],
        steps: [
          {
            id: uid(),
            name: 'Controle de custos operacionais',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 0,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'DRE e fluxo de caixa mensal',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 1,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Planejamento financeiro e metas',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 2,
            ai_points: [],
          },
        ],
      },
    ],
  },
  {
    id: uid(),
    name: 'Marketing',
    order_index: 3,
    phases: [
      {
        id: uid(),
        name: 'Conteúdo e Redes Sociais',
        order_index: 0,
        color: COLORS[2],
        steps: [
          {
            id: uid(),
            name: 'Planejamento de pauta mensal',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 0,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Produção de conteúdo (foto/vídeo/texto)',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 1,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Publicação e gestão do Instagram',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 2,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Gestão de anúncios (Meta Ads)',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 3,
            ai_points: [],
          },
        ],
      },
      {
        id: uid(),
        name: 'Captação e Relacionamento',
        order_index: 1,
        color: COLORS[5],
        steps: [
          {
            id: uid(),
            name: 'Prospecção ativa de clientes',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 0,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Atendimento de leads e qualificação',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 1,
            ai_points: [],
          },
          {
            id: uid(),
            name: 'Relacionamento pós-projeto e indicações',
            responsible: '',
            estimated_time: '',
            tools: '',
            notes: '',
            order_index: 2,
            ai_points: [],
          },
        ],
      },
    ],
  },
];
